`gluestick new` success message
TrueCar/gluestick pull request #450
Opened 2017-01-23 17:55 UTC by ferrannp

- The test needs to be reviewed after #406 
- Of course the message can be edited if we feel we want to add/remove something

2017-01-23 17:56 UTC, ferrannp commented on src/commands/new.js
> +  if (currentlyInProjectFolder) {
I checked that if you do not pass `projectName` we actually throw an error so this condition could be simplified.

2017-01-23 19:44 UTC, toddw requested changes

2017-01-23 19:44 UTC, toddw commented on src/commands/new.js
> +  logger.info(`    cd ${projectName}`);
should we add a line after this that says `     gluestick start`, before they can get anything in their browser?

2017-01-24 11:52 UTC, ferrannp commented on src/commands/new.js
> +  logger.info(`    cd ${projectName}`);
Yup, done :)

2017-01-24 22:47 UTC, merged