[WIP] Refactor autoUpgrade
TrueCar/gluestick pull request #517
Opened 2017-02-02 11:50 UTC by mike866

Solves #484

2017-02-02 12:06 UTC, ferrannp requested changes
@mike866 you are missing to unskip the `updatePackage.test.js` and probably refactor it too.

Also, do you know why is the `previous` folder for ?

It also looks like it broke `flow`.

2017-02-02 12:23 UTC, mike866 commented
@ferrannp Yeah it's still in progress :) Also I've asked @toddw about previous folder.

2017-02-03 01:42 UTC, toddw commented
Regarding: _.../previous/.babelrc_:
> That file can actually be removed. It was once used as part of upgrade functionality we had for the .babelrc file
> But it is no longer used

It should have been removed with https://github.com/TrueCar/gluestick/commit/99fe1614e3a252b4a4a91f99726e23c2fe9e3ef0#diff-56dac13b02c65e3b185373351e13081d but it slipped past us

2017-02-03 13:01 UTC, ferrannp approved these changes

2017-02-03 13:25 UTC, merged