Webpack configs
TrueCar/gluestick pull request #544
Opened 2017-02-07 11:00 UTC by zamotany

- [x] client dev config
- [ ] client prod config
- [ ] server dev config
- [ ] server prod config
- [ ] server entrypoint
- [ ] flow
- [x] webpack dev
- [ ] server debug
- [ ] pm2

2017-02-07 23:54 UTC, toddw commented
I really like the direction this is going! :+1:

2017-02-15 10:52 UTC, ferrannp requested changes

2017-02-15 10:52 UTC, ferrannp commented on packages/gluestick/.babelrc
> +        "closure-elimination"
Can you check if we need this `closure-elimination` for Jest?

2017-02-15 10:52 UTC, ferrannp commented on packages/gluestick/src/config/webpack/__tests__/buildEntries.test.js
> +}));
You can extract all these mocks in some file and reuse it in other tests like `buildServerEntries.test.js`.

2017-02-15 10:52 UTC, ferrannp commented on packages/gluestick/src/config/webpack/deepCopy.js
> +const deepCopy = (obj: Object) => {
Wouldn't be better to use existing implementation ? Like `cloneDeep` from lodash? Then we do not need to re-do it and re-test it.

2017-02-15 10:52 UTC, ferrannp commented on packages/gluestick/src/types.js
> +  config: any;
Can we avoid using `any` somehow ?

2017-02-15 11:04 UTC, zamotany commented on packages/gluestick/src/types.js
> +  config: any;
This should be done in separate issue, besides I didn't wrote those types, I only replaced commas with semicolons.

2017-02-15 11:14 UTC, michalchudziak requested changes

2017-02-15 11:14 UTC, michalchudziak commented on packages/gluestick/src/cli/execWithConfig.js
> +  { useGSConfig, useWebpackConfig, skipProjectConfig, skipEntryGeneration } = {},
How about typing this one 😇?

2017-02-15 11:14 UTC, michalchudziak commented on packages/gluestick/src/commands/start-server/runWithPM2.js
> +    instances: process.env.MAX_INSTANCES || (process.env.NODE_ENV === 'production' ? 1 : 1),
Why `(process.env.NODE_ENV === 'production' ? 1 : 1)`? I think it's not so valid 💃

2017-02-15 11:14 UTC, michalchudziak commented on packages/gluestick/src/commands/start.js
> +module.exports = exports = async ({ config, logger }, options) => {
Let's stick to `module.exports = () => {}`

2017-02-15 11:14 UTC, michalchudziak commented on packages/gluestick/src/config/compileGlueStickConfig.js
> +module.exports = exports = (plugins: Plugin[]): GSConfig => {
Same as above.

2017-02-15 11:14 UTC, mike866 commented on packages/gluestick/src/generator/templates/HomeApp.js
> +import Home from "../components/Home";
We are not supporting aliases anymore?

2017-02-15 11:18 UTC, zamotany commented on packages/gluestick/src/generator/templates/HomeApp.js
> +import Home from "../components/Home";
We do but `component` alias does not make any sense. Is it shared components or components from which app?

2017-02-15 11:42 UTC, michalchudziak approved these changes

2017-02-15 11:44 UTC, ferrannp approved these changes

2017-02-15 11:45 UTC, merged