[WIP] Refactor new command.
TrueCar/gluestick pull request #556
Opened 2017-02-08 10:48 UTC by mike866

2017-02-09 13:25 UTC, ferrannp requested changes
- It looks like the old tests templates for generated app (with `mocha`) got into this PR. We need to replace them again for the Jest ones.

- I also have problems with the path when generating a new app.

2017-02-10 15:04 UTC, zamotany requested changes

2017-02-10 15:04 UTC, zamotany commented on package.json
> +    "gluestick": "file:packages/gluestick",
What is that for?

2017-02-10 15:04 UTC, zamotany commented on packages/gluestick/src/generator/templates/package.js
> +        "gluestick": "../gluestick/packages/gluestick",
Should not be hardcoded. Value of gluestick should be dependent on value from CLI - `--dev <path>`.

2017-02-14 10:05 UTC, ferrannp approved these changes

2017-02-14 10:07 UTC, zamotany approved these changes

2017-02-14 10:08 UTC, merged