call gsBeforeRoute function from components before render
TrueCar/gluestick pull request #689
Opened 2017-03-01 12:16 UTC by dratwas

Solves #686

2017-03-01 12:26 UTC, zamotany reviewed
Why are code dublicated?? Looks like `getRouteComponents` is the same as in `gluestick-shared` package.

2017-03-01 12:48 UTC, zamotany requested changes
> This would run on the server side or in the browser depending on how you get there

it should run both on client (in browser) and on server - now it only runs on server
Besides there are code that is dublicated, the one from `gluestick-shared` should be used.

2017-03-02 12:23 UTC, dratwas commented
Now I use this one from gluestick-shared. Hooks work on a client but only when moves from one route to another not on init.

2017-03-02 13:46 UTC, zamotany approved these changes

2017-03-02 13:46 UTC, merged