Not check gluestick version on autoUpgrade
TrueCar/gluestick pull request #691
Opened 2017-03-01 13:54 UTC by lukewalczak

Solves #621

2017-03-01 15:17 UTC, ferrannp submitted a review, later dismissed
Did you take into consideration that this should **only** be done when we pass `--dev` flag ?

2017-03-01 15:59 UTC, zamotany requested changes

2017-03-01 15:59 UTC, zamotany commented on packages/gluestick/src/autoUpgrade/checkForMismatch.js
> +    if (dev && dep === 'gluestick' && !/\d\.\d\.\d.*/.test(projectPackage.dependencies[dep])) {
Replace this regex with: `\d+\.\d+\.\d+.*`

2017-03-02 09:43 UTC, michalchudziak approved these changes

2017-03-02 09:44 UTC, zamotany approved these changes

2017-03-02 10:25 UTC, merged