Separate package for gluestick generators
TrueCar/gluestick pull request #712
Opened 2017-03-03 14:09 UTC by mike866

WIP

2017-03-06 11:45 UTC, mike866 commented
Freezing this one due to symlink idea.

2017-03-09 11:37 UTC, mike866 commented
We need to replace `"gluestick-generators": "file:<PATH>"` with `rc` version on next release.

2017-03-09 12:17 UTC, zamotany requested changes

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/src/index.js
> +};
It's also possible to export some function as a default, and other when using dot:
```
module.exports = () => '1';
module.exports.fn = () => '2';
```
so requiring will be:
```
const fnDefault = require('some-file');
const fnOther = require('some-file').fn;
```
but I'm fine with object also.

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-cli/package.json
> +    "gluestick-generators": "file:../gluestick-generators",
Not sure if this is ok

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/package.json
> +    "test-watch": "jest --watch",
not needed

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/package.json
> +    "debug": "node --inspect --debug-brk ./node_modules/.bin/jest -i --env ./test/jestEnvironmentNodeDebug.js",
also not needed

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/package.json
> +    "postpublish": "./docker/create-base-image.js",
same as above

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/package.json
> +    "update-version": "npm version",
same as above

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/package.json
> +    "postupdate-version": "./docker/generate-dockerfile.js"
same as above

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/package.json
> +    "temp": "0.8.3"
I believe this is not needed

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick-generators/src/requireGenerator.js
> +const PATH_TO_GLUESTICK_TEMPLATES = '../../gluestick/generator/predefined';
maybe use `require.resolve` and split it on `gluestick` to get always valid path to gluestick?

2017-03-09 12:17 UTC, zamotany commented on packages/gluestick/package.json
> +    "gluestick-generators": "file:../gluestick-generators",
Also not sure about this

2017-03-09 12:32 UTC, ferrannp commented on packages/gluestick-generators/src/index.js
> +};
I prefer this over the `.default` :)

2017-03-09 12:33 UTC, ferrannp commented on packages/gluestick-generators/package.json
> +    "temp": "0.8.3"
Yea this is not needed. It is only used in `destroy.test.js` from `gluestick` package and it will likely go away from there soon too.

2017-03-09 12:52 UTC, mike866 commented on packages/gluestick-generators/src/requireGenerator.js
> +const PATH_TO_GLUESTICK_TEMPLATES = '../../gluestick/generator/predefined';
I'm not sure about this solution, in fact it results in `Cannot find module 'gluestick'`.

2017-03-09 13:59 UTC, zamotany requested changes

2017-03-09 13:59 UTC, zamotany commented on packages/gluestick-generators/src/requireGenerator.js
> +const PATH_TO_GLUESTICK_TEMPLATES = '../../gluestick/generator/predefined';
In that case extract path to gluestick templates to `getPossiblePaths` and `requireGeneratorConfig` argument and pass it from `generator.js`.

2017-03-10 15:14 UTC, merged