Exported gs-shared from gluestick
TrueCar/gluestick pull request #815
Opened 2017-03-16 12:59 UTC by lukewalczak

Solves #810

2017-03-16 13:14 UTC, mike866 commented
Please move files from `gluestick-shared` package to `shared` folder in `gluestick` then require it from `require('./shared')`.

2017-03-20 13:48 UTC, zamotany approved these changes

2017-03-20 15:13 UTC, ferrannp approved these changes

2017-03-20 15:14 UTC, ferrannp requested changes
CI is failing https://circleci.com/gh/TrueCar/gluestick/1195

2017-03-20 15:18 UTC, merged