Dratwas/support ssr caching
TrueCar/gluestick pull request #898
Opened 2017-04-04 11:47 UTC by dratwas

2017-04-04 12:27 UTC, zamotany reviewed
I think we need to document this, right?

2017-04-04 21:14 UTC, zamotany requested changes

2017-04-04 21:14 UTC, zamotany commented on docs/CachingAndHooks.md
> +Gluestick supprots SSR component caching by using [`electrode-react-ssr-caching`](https://github.com/electrode-io/electrode-react-ssr-caching).
`supprots`? 😄

2017-04-04 21:14 UTC, zamotany commented on packages/gluestick/src/renderer/helpers/cacheManager.js
> +    if (isProduction && !!config && !!config.components) {
Are those `!!` really needed?? Both `config` and `config.components` will be evaluated to boolean.

2017-04-05 09:16 UTC, dratwas commented on packages/gluestick/src/renderer/helpers/cacheManager.js
> +    if (isProduction && !!config && !!config.components) {
Honestly it's no needed, i was looking at old gluestick :)

2017-04-05 11:59 UTC, zamotany approved these changes

2017-04-05 11:59 UTC, merged