Migration guide
TrueCar/gluestick pull request #937
Opened 2017-04-18 12:11 UTC by zamotany

#Ref: #933

2017-04-20 10:00 UTC, dratwas requested changes

2017-04-20 10:00 UTC, dratwas commented on docs/MigrationGuide.md
> +now you must specify *who onws this component* - whether it's `shared` or inside some app:
typo in "owns"

2017-04-20 10:00 UTC, dratwas commented on docs/MigrationGuide.md
> +import SomeComponen from 'shared/components/SomeComponen';
typo: `Component` the same is below ")

2017-04-20 10:00 UTC, dratwas commented on docs/MigrationGuide.md
> +Previusly `reducers/index.js` file was re-exporting reducers:
`Previously`

2017-04-20 22:06 UTC, trungly commented
I had a lot of grammar suggestions, but they were too numerous and minor.  Instead I just pushed a commit to fix those.  Hope that's okay.  I believe all 3 of the typos pointed out by @dratwas are included.

2017-04-24 19:33 UTC, saltycrane commented
Did you use https://github.com/skovhus/jest-codemods to migrate tests to Jest? Are there any gotchas we should look out for?

2017-04-27 18:47 UTC, saltycrane commented
Another change I didn't see: `promiseMiddleware` changed to use `payload` instead of `value`.

2017-04-28 08:28 UTC, zamotany commented
@saltycrane Good catch, I forgot about it.

2017-04-28 16:55 UTC, saltycrane commented
@zamotany Thank you for the migration guide. I was very helpful.

2017-07-07 10:47 UTC, merged